Globs:
  - src/**/*.cr
  - spec/**/*.cr

Documentation/Documentation:
  Enabled: false

Documentation/DocumentationAdmonition:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Naming/BlockParameterName:
  Enabled: false

# There is nothing to prove that this affects performance
Performance/AnyInsteadOfEmpty:
  Enabled: false
